# !!!!!! Rename this file to local_secrets.toml (in project root) and add username and passcode below !!!!!!

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "your email"
password = "your passcode"
